### ISSUE TITLE
Unreadable Notebook

### ISSUE THREAD

**Issue by JoyJulianGomes** [OmkarPathak/Data-Structures-using-Python#10]
Hi Omkar!!
Firstly, thanks for this awesome repo. I was facing trouble with opening the Queue.ipynb file, please check the attached image.
![capture](https://user-images.githubusercontent.com/22003711/50358437-80b96880-0583-11e9-89ad-cad8a7cfdaf9.PNG)

**Comment by OmkarPathak** [comment]
@JoyJulianGones this was caused by previous commit. I will revert it soon. Thanks for reporting

**Comment by OmkarPathak** [comment]
Hi @JoyJulianGomes, now it should work :smile:
