### ISSUE TITLE
Bug in Queue Program example. It doesn't respect First In First Out property

### ISSUE THREAD

**Issue by gsundeep-tech** [OmkarPathak/Data-Structures-using-Python#2]
Hi Omkar,

Append and Pop will add and remove the elements at the end of list.
Queue follows first come first serve property(FIFO). consider the following example

>>> a = []
>>> a.enqueue(1)  # adding the element to empty queue
>>> a
[1]
>>> a.enqueue(2) # adding the second element
[1, 2]
>>> a.dequeue() # removing the first element
>>> a
[2]

To remove the first element use the pop(0) instead of pop() 
Nice Collection of tutorials. Great Work!!

Thanks,
Sundeep Gullapudi.

**Comment by OmkarPathak** [comment]
Thank You for reporting. I have made the necessary changes! :+1:  :smile:

**Comment by gsundeep-tech** [comment]
I think you forgot to do the changes in Queue jupyter notebook
