### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by Rakesh148** [OmkarPathak/Data-Structures-using-Python#32]
#Array.ipynb file
'The array elements can be accessed in constant time by using the index of the **parliculnr** element as the subscript.'

**Comment by imalK96** [comment]
Can I take this issue up?

**Comment by OmkarPathak** [comment]
@imalK96 go ahead

**Comment by imalK96** [comment]
@OmkarPathak I have fixed the typo https://github.com/OmkarPathak/Data-Structures-using-Python/pull/33
